find_path(LIBHARU_INCLUDE_DIR NAMES hpdf.h PATHS ${CONAN_INCLUDE_DIRS_LIBHARU})
find_library(LIBHARU_LIBRARY NAMES ${CONAN_LIBS_LIBHARU} PATHS ${CONAN_LIB_DIRS_LIBHARU})

set(LIBHARU_FOUND TRUE)  
set(LIBHARU_INCLUDE_DIRS ${LIBHARU_INCLUDE_DIR})
set(LIBHARU_LIBRARIES ${LIBHARU_LIBRARY})
mark_as_advanced(LIBHARU_LIBRARY LIBHARU_INCLUDE_DIR)
